# Generated by Django 4.1.2 on 2022-11-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='task_name',
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(verbose_name=''),
        ),
    ]
