# Generated by Django 4.0 on 2022-11-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_rename_name_task_task_name_alter_task_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_no',
            new_name='priority',
        ),
    ]
